// ================================================================
// items_food.js — 음식 아이템 (50개)
// category: 'food'
// 즉시 사용, 인벤토리에서 사용 버튼 클릭
// ================================================================

window.ITEMS_FOOD = {
  food_001: {
    id: 'food_001', category: 'food',
    name: '얼어붙은 아메리카노', icon: '☕', price: 2,
    desc: 'SP +25',
    effect: { sp: 25 },
  },
  food_002: {
    id: 'food_002', category: 'food',
    name: '청룡탕 어묵꼬치', icon: '🍢', price: 2,
    desc: 'HP +15',
    effect: { hp: 15 },
  },
  food_003: {
    id: 'food_003', category: 'food',
    name: '중앙대 도시락', icon: '🍱', price: 5,
    desc: 'HP +30 · SP +15',
    effect: { hp: 30, sp: 15 },
  },
  food_004: {
    id: 'food_004', category: 'food',
    name: '에너지 드링크', icon: '🥤', price: 8,
    desc: 'SP 완전 회복',
    effect: { sp_full: true },
  },
  food_005: {
    id: 'food_005', category: 'food',
    name: '학식 한우 특선', icon: '🥩', price: 12,
    desc: 'HP +50 · 전투 데미지 +5 (1회)',
    effect: { hp: 50, battle_dmg_once: 5 },
  },
  food_006: {
    id: 'food_006', category: 'food',
    name: '푸앙이 쿠키', icon: '🍪', price: 6,
    desc: '호감도 +5',
    effect: { favor: 5 },
  },
  food_007: {
    id: 'food_007', category: 'food',
    name: '편의점 삼각김밥', icon: '🍙', price: 1,
    desc: 'HP +8',
    effect: { hp: 8 },
  },
  food_008: {
    id: 'food_008', category: 'food',
    name: '과방 커피믹스', icon: '🫖', price: 1,
    desc: 'SP +10',
    effect: { sp: 10 },
  },
  food_009: {
    id: 'food_009', category: 'food',
    name: '청룡탕 라면', icon: '🍜', price: 3,
    desc: 'HP +20 · SP +10',
    effect: { hp: 20, sp: 10 },
  },
  food_010: {
    id: 'food_010', category: 'food',
    name: '중앙대 기념 케이크', icon: '🎂', price: 15,
    desc: '호감도 +10',
    effect: { favor: 10 },
  },
  food_011: {
    id: 'food_011', category: 'food',
    name: '학식 순두부찌개', icon: '🍲', price: 4,
    desc: 'HP +25 · 디버프 제거',
    effect: { hp: 25, cure: true },
  },
  food_012: {
    id: 'food_012', category: 'food',
    name: '후식 요구르트', icon: '🥛', price: 3,
    desc: '3턴 HP +5 재생',
    effect: { regen_hp: 5, regen_turns: 3 },
  },
  food_013: {
    id: 'food_013', category: 'food',
    name: '에너지바', icon: '🌾', price: 3,
    desc: 'HP +10 · SP +10',
    effect: { hp: 10, sp: 10 },
  },
  food_014: {
    id: 'food_014', category: 'food',
    name: '버블티', icon: '🧋', price: 4,
    desc: 'SP +20 · 호감도 +2',
    effect: { sp: 20, favor: 2 },
  },
  food_015: {
    id: 'food_015', category: 'food',
    name: '치킨 (야식)', icon: '🍗', price: 8,
    desc: 'HP +40 · 다음 전투 SP -10',
    effect: { hp: 40, battle_sp_penalty: 10 },
  },
  food_016: {
    id: 'food_016', category: 'food',
    name: '컵라면', icon: '🥣', price: 2,
    desc: 'HP +12 · SP +8',
    effect: { hp: 12, sp: 8 },
  },
  food_017: {
    id: 'food_017', category: 'food',
    name: '초코바', icon: '🍫', price: 3,
    desc: 'SP +15 · 집중력 +10% (1회)',
    effect: { sp: 15, focus_once: 10 },
  },
  food_018: {
    id: 'food_018', category: 'food',
    name: '비타민 음료', icon: '💊', price: 10,
    desc: '최대 HP +5 (영구)',
    effect: { max_hp_perm: 5 },
  },
  food_019: {
    id: 'food_019', category: 'food',
    name: '학식 스페셜 정식', icon: '🍽️', price: 7,
    desc: 'HP +35 · SP +35',
    effect: { hp: 35, sp: 35 },
  },
  food_020: {
    id: 'food_020', category: 'food',
    name: '푸앙이 도넛', icon: '🍩', price: 8,
    desc: '호감도 +8 · HP +10',
    effect: { favor: 8, hp: 10 },
  },
  food_021: {
    id: 'food_021', category: 'food',
    name: '중앙대 막걸리', icon: '🍶', price: 5,
    desc: 'HP +30 · 명중률 -20% (1전투)',
    effect: { hp: 30, acc_penalty_once: 20 },
  },
  food_022: {
    id: 'food_022', category: 'food',
    name: '아이스크림', icon: '🍦', price: 2,
    desc: 'SP +12',
    effect: { sp: 12 },
  },
  food_023: {
    id: 'food_023', category: 'food',
    name: '핫초코', icon: '🍵', price: 3,
    desc: 'HP +18 · SP +8',
    effect: { hp: 18, sp: 8 },
  },
  food_024: {
    id: 'food_024', category: 'food',
    name: '과일 샐러드', icon: '🥗', price: 5,
    desc: 'HP +12 · 최대 HP +2 (영구)',
    effect: { hp: 12, max_hp_perm: 2 },
  },
  food_025: {
    id: 'food_025', category: 'food',
    name: '단백질 쉐이크', icon: '🏋️', price: 6,
    desc: '체육관 효율 +30% (1회)',
    effect: { gym_bonus_once: 30 },
  },
  food_026: {
    id: 'food_026', category: 'food',
    name: '편의점 샌드위치', icon: '🥪', price: 2,
    desc: 'HP +15 · SP +5',
    effect: { hp: 15, sp: 5 },
  },
  food_027: {
    id: 'food_027', category: 'food',
    name: '학식 김치찌개', icon: '🫙', price: 3,
    desc: 'HP +22',
    effect: { hp: 22 },
  },
  food_028: {
    id: 'food_028', category: 'food',
    name: '타코야끼', icon: '🐙', price: 4,
    desc: 'SP +18 · 호감도 +3',
    effect: { sp: 18, favor: 3 },
  },
  food_029: {
    id: 'food_029', category: 'food',
    name: '붕어빵', icon: '🐟', price: 1,
    desc: 'HP +10 · 호감도 +2',
    effect: { hp: 10, favor: 2 },
  },
  food_030: {
    id: 'food_030', category: 'food',
    name: '떡볶이', icon: '🌶️', price: 4,
    desc: 'HP +20 · 전투 공격력 +3 (1회)',
    effect: { hp: 20, battle_dmg_once: 3 },
  },
  food_031: {
    id: 'food_031', category: 'food',
    name: '마라탕', icon: '🫕', price: 6,
    desc: 'HP +35 · SP -10',
    effect: { hp: 35, sp: -10 },
  },
  food_032: {
    id: 'food_032', category: 'food',
    name: '초밥 세트', icon: '🍣', price: 10,
    desc: 'HP +40 · SP +20',
    effect: { hp: 40, sp: 20 },
  },
  food_033: {
    id: 'food_033', category: 'food',
    name: '피자 한 조각', icon: '🍕', price: 5,
    desc: 'HP +25 · SP +10',
    effect: { hp: 25, sp: 10 },
  },
  food_034: {
    id: 'food_034', category: 'food',
    name: '햄버거 세트', icon: '🍔', price: 6,
    desc: 'HP +30 · SP +15',
    effect: { hp: 30, sp: 15 },
  },
  food_035: {
    id: 'food_035', category: 'food',
    name: '스무디', icon: '🍹', price: 4,
    desc: 'SP +22 · 집중력 +5%',
    effect: { sp: 22, focus_once: 5 },
  },
  food_036: {
    id: 'food_036', category: 'food',
    name: '꿀물', icon: '🍯', price: 2,
    desc: 'HP +8 · 상태이상 회복',
    effect: { hp: 8, cure: true },
  },
  food_037: {
    id: 'food_037', category: 'food',
    name: '홍삼 음료', icon: '🧃', price: 12,
    desc: '최대 SP +5 (영구)',
    effect: { max_sp_perm: 5 },
  },
  food_038: {
    id: 'food_038', category: 'food',
    name: '프로틴 바', icon: '🏃', price: 7,
    desc: '체육관 훈련 HP 보너스 +5',
    effect: { gym_hp_bonus: 5 },
  },
  food_039: {
    id: 'food_039', category: 'food',
    name: '학식 돈까스', icon: '🍖', price: 5,
    desc: 'HP +28 · SP +12',
    effect: { hp: 28, sp: 12 },
  },
  food_040: {
    id: 'food_040', category: 'food',
    name: '편의점 도시락', icon: '📦', price: 3,
    desc: 'HP +20 · SP +8',
    effect: { hp: 20, sp: 8 },
  },
  food_041: {
    id: 'food_041', category: 'food',
    name: '블루베리 스무디', icon: '🫐', price: 5,
    desc: '도서관 집중력 +15% (1회)',
    effect: { lib_focus_bonus_once: 15 },
  },
  food_042: {
    id: 'food_042', category: 'food',
    name: '카페라떼', icon: '🫗', price: 3,
    desc: 'SP +18 · 호감도 +1',
    effect: { sp: 18, favor: 1 },
  },
  food_043: {
    id: 'food_043', category: 'food',
    name: '생과일주스', icon: '🍊', price: 4,
    desc: 'HP +15 · 독 디버프 제거',
    effect: { hp: 15, cure_poison: true },
  },
  food_044: {
    id: 'food_044', category: 'food',
    name: '푸앙이 마카롱', icon: '🫶', price: 10,
    desc: '호감도 +12',
    effect: { favor: 12 },
  },
  food_045: {
    id: 'food_045', category: 'food',
    name: '청룡 에너지볼', icon: '⚡', price: 15,
    desc: 'HP +20 · SP +20 · 전투 데미지 +3',
    effect: { hp: 20, sp: 20, battle_dmg_once: 3 },
  },
  food_046: {
    id: 'food_046', category: 'food',
    name: '학식 냉면', icon: '🍝', price: 6,
    desc: 'SP +30 · HP +10',
    effect: { sp: 30, hp: 10 },
  },
  food_047: {
    id: 'food_047', category: 'food',
    name: '소떡소떡', icon: '🍡', price: 3,
    desc: 'HP +18 · 호감도 +2',
    effect: { hp: 18, favor: 2 },
  },
  food_048: {
    id: 'food_048', category: 'food',
    name: '중앙대 특제 쌈밥', icon: '🥬', price: 20,
    desc: 'HP 완전 회복',
    effect: { hp_full: true },
  },
  food_049: {
    id: 'food_049', category: 'food',
    name: '이면 세계 포션', icon: '🧪', price: 25,
    desc: 'HP +60 · SP +30',
    effect: { hp: 60, sp: 30 },
  },
  food_050: {
    id: 'food_050', category: 'food',
    name: '푸앙이 특제 도시락', icon: '🐉', price: 35,
    desc: 'HP·SP 완전 회복 · 호감도 +5',
    effect: { hp_full: true, sp_full: true, favor: 5 },
  },
};
