// ================================================================
// items_equip.js — 착용 아이템 (50개)
// category: 'equip'
// ================================================================
window.ITEMS_EQUIP = {
  // ── 기존 호환 id 유지 ──
  dmg_boost: { id:'dmg_boost', category:'equip', name:'데미지 부스터', icon:'🔥', price:8,  desc:'다음 전투 데미지 +50%', effect:{ battle_dmg_pct_once:50 }, clerk:'전투 전에 꼭 챙겨가세요 💪' },
  shield:    { id:'shield',    category:'equip', name:'방어막',        icon:'🛡️', price:8,  desc:'다음 전투 피해 -50%',   effect:{ dmg_reduce_pct_once:50 }, clerk:'안전이 최우선이죠! 🛡️' },
  speed:     { id:'speed',     category:'equip', name:'집중력 포션',   icon:'⚡', price:8,  desc:'다음 전투 데미지 +50%', effect:{ battle_dmg_pct_once:50 } },
  regen:     { id:'regen',     category:'equip', name:'재생 포션',     icon:'🌿', price:10, desc:'전투 중 매 턴 HP +5',   effect:{ hp_regen_per_turn:5 } },
  lucky:     { id:'lucky',     category:'equip', name:'행운의 시약',   icon:'🍀', price:12, desc:'도서관 보상 2배',        effect:{ lib_reward_multiplier:2 } },
  cloak:     { id:'cloak',     category:'equip', name:'투명 망토',     icon:'🫥', price:18, desc:'이면세계 몬스터 조우율 -30%', effect:{ explore_encounter_pct:-30 }, clerk:'이면세계 탐험가 필수템! 🫥' },
  charm:     { id:'charm',     category:'equip', name:'청룡 부적',     icon:'🧧', price:12, desc:'전투 사망 시 HP 15로 부활 (1회)', effect:{ last_stand:15 }, clerk:'위기의 순간 당신을 지켜줘요 🧧' },

  // ── 신규 착용 아이템 ──
  equip_id:     { id:'equip_id',     category:'equip', name:'중앙대 학생증',    icon:'🪪', price:8,  desc:'최대 HP +10',              effect:{ max_hp:10 } },
  equip_jumper: { id:'equip_jumper', category:'equip', name:'공대 점퍼',         icon:'🧥', price:10, desc:'전투 데미지 +5',            effect:{ battle_dmg:5 } },
  equip_libcard:{ id:'equip_libcard',category:'equip', name:'도서관 회원증',     icon:'📗', price:8,  desc:'도서관 보상 +2',            effect:{ lib_reward:2 } },
  equip_badge:  { id:'equip_badge',  category:'equip', name:'청룡 배지',         icon:'🏅', price:20, desc:'모든 스탯 +5%',             effect:{ all_stat_pct:5 } },
  equip_muffler:{ id:'equip_muffler',category:'equip', name:'푸앙이 머플러',     icon:'🧣', price:15, desc:'피해 감소 10%',             effect:{ dmg_reduce_pct:10 } },
  equip_coat:   { id:'equip_coat',   category:'equip', name:'이면 세계 코트',    icon:'🥼', price:18, desc:'전투 시작 HP +20',          effect:{ battle_start_hp:20 } },
  equip_earphone:{ id:'equip_earphone',category:'equip',name:'이어폰',           icon:'🎧', price:8,  desc:'도서관 보상 +2',            effect:{ lib_reward:2 } },
  equip_bag:    { id:'equip_bag',    category:'equip', name:'노트북 가방',        icon:'🎒', price:10, desc:'데이터 조각 보관량 +20',    effect:{ data_capacity:20 } },
  equip_hoodie: { id:'equip_hoodie', category:'equip', name:'중앙대 후드티',      icon:'👕', price:12, desc:'방어력 +3 · 호감도 +3',     effect:{ defense:3, favor:3 } },
  equip_planner:{ id:'equip_planner',category:'equip', name:'스터디 플래너',     icon:'📒', price:10, desc:'공부 횟수 +2',              effect:{ study_count:2 } },
  equip_battery:{ id:'equip_battery',category:'equip', name:'보조배터리',        icon:'🔋', price:14, desc:'SP 매 턴 +3 자동회복',      effect:{ sp_regen_per_turn:3 } },
  equip_glasses:{ id:'equip_glasses',category:'equip', name:'청룡 안경',         icon:'👓', price:15, desc:'적 약점 노출 +20%',         effect:{ weakness_reveal_pct:20 } },
  equip_calc:   { id:'equip_calc',   category:'equip', name:'공학 계산기',        icon:'🔢', price:12, desc:'데미지 +3',                 effect:{ battle_dmg:3 } },
  equip_gym:    { id:'equip_gym',    category:'equip', name:'중앙대 체육복',      icon:'🩱', price:10, desc:'체육관 훈련 효율 +50%',     effect:{ gym_efficiency_pct:50 } },
  equip_book:   { id:'equip_book',   category:'equip', name:'두꺼운 전공책',      icon:'📚', price:14, desc:'피해 -8',                   effect:{ dmg_reduce:8 } },
  equip_coin:   { id:'equip_coin',   category:'equip', name:'행운의 동전',        icon:'🪙', price:18, desc:'주사위 최솟값 +2',          effect:{ dice_min:2 } },
  equip_necklace:{ id:'equip_necklace',category:'equip',name:'블루미르 목걸이',   icon:'📿', price:16, desc:'호감도 +5 · 최대 SP +5',    effect:{ favor:5, max_sp:5 } },
  equip_earbud: { id:'equip_earbud', category:'equip', name:'무선 이어버드',      icon:'🎵', price:12, desc:'도서관 집중력 감소 -10%',   effect:{ lib_focus_decay_pct:-10 } },
  equip_bike:   { id:'equip_bike',   category:'equip', name:'캠퍼스 자전거',      icon:'🚲', price:8,  desc:'이동 SP 소모 없음',         effect:{ move_sp_cost:0 } },
  equip_armband:{ id:'equip_armband',category:'equip', name:'학생회 완장',        icon:'🎖️', price:14, desc:'축제 보상 +50%',            effect:{ festival_reward_pct:50 } },
  equip_key:    { id:'equip_key',    category:'equip', name:'연구실 열쇠',        icon:'🔑', price:16, desc:'310관 강화 비용 -20%',      effect:{ lab_cost_pct:-20 } },
  equip_cape:   { id:'equip_cape',   category:'equip', name:'이면 세계 망토',     icon:'🦸', price:20, desc:'진입 시 HP +10%',           effect:{ enter_hp_pct:10 } },
  equip_shoes:  { id:'equip_shoes',  category:'equip', name:'청룡산 등산화',      icon:'👟', price:22, desc:'보스 HP -10%',              effect:{ boss_hp_pct:-10 } },
  equip_ring:   { id:'equip_ring',   category:'equip', name:'중앙대 졸업반지',    icon:'💍', price:50, desc:'모든 효과 +10%',            effect:{ all_effect_pct:10 } },
  equip_shield2:{ id:'equip_shield2',category:'equip', name:'청룡 방패',          icon:'🛡️', price:25, desc:'피해 -15 · 최대 HP +10',   effect:{ dmg_reduce:15, max_hp:10 } },
  equip_gown:   { id:'equip_gown',   category:'equip', name:'연구원 가운',        icon:'🥽', price:12, desc:'실험실 제조 비용 -2',       effect:{ lab2_cost:-2 } },
  equip_band:   { id:'equip_band',   category:'equip', name:'스포츠 밴드',        icon:'⌚', price:10, desc:'체육관 체력 소모 -10%',     effect:{ gym_hp_cost_pct:-10 } },
  equip_map:    { id:'equip_map',    category:'equip', name:'캠퍼스 지도',         icon:'🗺️', price:5,  desc:'장소 툴팁 상세 표시',       effect:{ map_tooltip_detail:true } },
  equip_coupon: { id:'equip_coupon', category:'equip', name:'학식 쿠폰북',        icon:'🎟️', price:15, desc:'학생식당 가격 -1 (영구)',    effect:{ cafeteria_cost:-1 } },
  equip_pen:    { id:'equip_pen',    category:'equip', name:'청룡 깃털 펜',       icon:'🪶', price:10, desc:'퀴즈 정답 보상 +3',         effect:{ quiz_reward:3 } },
  equip_note:   { id:'equip_note',   category:'equip', name:'마법 노트',           icon:'📓', price:14, desc:'도서관 보상 최솟값 +1',     effect:{ lib_reward_min:1 } },
  equip_cap:    { id:'equip_cap',    category:'equip', name:'중앙대 야구 모자',    icon:'🧢', price:8,  desc:'햇빛 디버프 면역',          effect:{ sunlight_immune:true } },
  equip_robot:  { id:'equip_robot',  category:'equip', name:'공대 로봇 부품',      icon:'🤖', price:20, desc:'전투 자동 방어 1회',        effect:{ auto_shield:1 } },
  equip_glove:  { id:'equip_glove',  category:'equip', name:'이면 세계 장갑',      icon:'🖐️', price:22, desc:'크리티컬 확률 +15%',        effect:{ crit_pct:15 } },
  equip_amulet: { id:'equip_amulet', category:'equip', name:'블루미르 부적',       icon:'🧿', price:30, desc:'전투 패배 시 HP 1 유지 (1회)', effect:{ last_stand:1 } },
  equip_tattoo: { id:'equip_tattoo', category:'equip', name:'청룡 문신 스티커',    icon:'🔱', price:18, desc:'전투 데미지 +8',            effect:{ battle_dmg:8 } },
  equip_scarf:  { id:'equip_scarf',  category:'equip', name:'중앙대 스카프',       icon:'🎀', price:20, desc:'최대 HP +15 · 최대 SP +5',  effect:{ max_hp:15, max_sp:5 } },
  equip_goggle: { id:'equip_goggle', category:'equip', name:'연구실 고글',         icon:'🔭', price:12, desc:'실험실 성공률 +20%',        effect:{ lab2_success_pct:20 } },
  equip_backpack:{ id:'equip_backpack',category:'equip',name:'푸앙이 배낭',        icon:'🪅', price:15, desc:'인벤토리 슬롯 +3',          effect:{ inv_slots:3 } },
  equip_watch:  { id:'equip_watch',  category:'equip', name:'청룡 시계',           icon:'⏱️', price:16, desc:'도서관 공부 시간 -1초',     effect:{ lib_time:-1 } },
  equip_chain:  { id:'equip_chain',  category:'equip', name:'중앙대 체인',         icon:'⛓️', price:24, desc:'보스 등장 시 데미지 +10',   effect:{ boss_dmg:10 } },
  equip_boots:  { id:'equip_boots',  category:'equip', name:'이면 세계 부츠',      icon:'👢', price:20, desc:'전투 회피율 +10%',          effect:{ dodge_pct:10 } },
  equip_stamp:  { id:'equip_stamp',  category:'equip', name:'학생처 도장',         icon:'🔏', price:18, desc:'의무실 무료 횟수 +1',       effect:{ clinic_free:1 } },
  equip_crown:  { id:'equip_crown',  category:'equip', name:'청룡 왕관',           icon:'👑', price:40, desc:'호감도 +10 · 모든 스탯 +3%',effect:{ favor:10, all_stat_pct:3 } },
  equip_slot:   { id:'equip_slot',   category:'equip', name:'마법 계산기',         icon:'🎰', price:15, desc:'슬롯머신 당첨 확률 +5%',    effect:{ slot_luck_pct:5 } },
  equip_sword:  { id:'equip_sword',  category:'equip', name:'이면 세계 검',        icon:'⚔️', price:28, desc:'전투 데미지 +12 · 방어 -5', effect:{ battle_dmg:12, dmg_reduce:-5 } },
  equip_blueshield:{ id:'equip_blueshield',category:'equip',name:'블루미르 방패',  icon:'🔰', price:28, desc:'피해 -20 · 데미지 -5',      effect:{ dmg_reduce:20, battle_dmg:-5 } },
  equip_armor:  { id:'equip_armor',  category:'equip', name:'청룡 갑옷',           icon:'🪬', price:45, desc:'최대 HP +30 · 피해 -10',    effect:{ max_hp:30, dmg_reduce:10 } },
  equip_grimoire:{ id:'equip_grimoire',category:'equip',name:'이면 세계 마법서',   icon:'📖', price:48, desc:'모든 스킬 데미지 +20%',     effect:{ skill_dmg_pct:20 } },
  equip_sacred: { id:'equip_sacred', category:'equip', name:'푸앙이 성물',         icon:'✨', price:99, desc:'모든 스탯 최대 · 호감도 +20',effect:{ all_stat_max:true, favor:20 } },
};
