// ================================================================
// items_food.js — 음식 아이템 (50개)
// category: 'food'
// ================================================================
window.ITEMS_FOOD = {
  // ── 기존 호환 id 유지 ──
  hp_potion:   { id:'hp_potion',   category:'food', name:'HP 포션',       icon:'🧃', price:5,  desc:'HP +30 회복',         effect:{ hp:30 },           clerk:'체력 회복에 딱이죠~ 많이 사 가세요!' },
  sp_potion:   { id:'sp_potion',   category:'food', name:'SP 포션',       icon:'💙', price:4,  desc:'SP +20 회복',         effect:{ sp:20 },           clerk:'집중력 포션이에요! 공부할 때 좋아요 😊' },
  full_potion: { id:'full_potion', category:'food', name:'풀 회복 포션',  icon:'✨', price:15, desc:'HP·SP 완전 회복',     effect:{ hp_full:true, sp_full:true }, clerk:'저희 가게 최고 인기 상품이에요! ✨' },
  mem_potion:  { id:'mem_potion',  category:'food', name:'기억력 포션',   icon:'🧠', price:10, desc:'도서관 집중력 +20% (1회)', effect:{ lib_focus_bonus_once:20 }, clerk:'공부 전에 딱이에요! 🧠' },

  // ── 신규 음식 아이템 ──
  food_ame:    { id:'food_ame',    category:'food', name:'얼어붙은 아메리카노', icon:'☕', price:2,  desc:'SP +25',             effect:{ sp:25 } },
  food_odeng:  { id:'food_odeng',  category:'food', name:'청룡탕 어묵꼬치',     icon:'🍢', price:2,  desc:'HP +15',             effect:{ hp:15 } },
  food_dosirak:{ id:'food_dosirak',category:'food', name:'중앙대 도시락',       icon:'🍱', price:5,  desc:'HP +30 · SP +15',    effect:{ hp:30, sp:15 } },
  food_energy: { id:'food_energy', category:'food', name:'에너지 드링크',       icon:'🥤', price:8,  desc:'SP 완전 회복',        effect:{ sp_full:true } },
  food_hanwoo: { id:'food_hanwoo', category:'food', name:'학식 한우 특선',      icon:'🥩', price:12, desc:'HP +50 · 전투 데미지 +5 (1회)', effect:{ hp:50, battle_dmg_once:5 } },
  food_cookie: { id:'food_cookie', category:'food', name:'푸앙이 쿠키',         icon:'🍪', price:6,  desc:'호감도 +5',           effect:{ favor:5 } },
  food_samgak: { id:'food_samgak', category:'food', name:'편의점 삼각김밥',     icon:'🍙', price:1,  desc:'HP +8',              effect:{ hp:8 } },
  food_coffee: { id:'food_coffee', category:'food', name:'과방 커피믹스',       icon:'🫖', price:1,  desc:'SP +10',             effect:{ sp:10 } },
  food_ramen:  { id:'food_ramen',  category:'food', name:'청룡탕 라면',         icon:'🍜', price:3,  desc:'HP +20 · SP +10',    effect:{ hp:20, sp:10 } },
  food_cake:   { id:'food_cake',   category:'food', name:'중앙대 기념 케이크',  icon:'🎂', price:15, desc:'호감도 +10',          effect:{ favor:10 } },
  food_tofu:   { id:'food_tofu',   category:'food', name:'학식 순두부찌개',     icon:'🍲', price:4,  desc:'HP +25 · 디버프 제거',effect:{ hp:25, cure:true } },
  food_yogurt: { id:'food_yogurt', category:'food', name:'후식 요구르트',       icon:'🥛', price:3,  desc:'3턴 HP +5 재생',      effect:{ regen_hp:5, regen_turns:3 } },
  food_bar:    { id:'food_bar',    category:'food', name:'에너지바',            icon:'🌾', price:3,  desc:'HP +10 · SP +10',    effect:{ hp:10, sp:10 } },
  food_bubble: { id:'food_bubble', category:'food', name:'버블티',              icon:'🧋', price:4,  desc:'SP +20 · 호감도 +2',  effect:{ sp:20, favor:2 } },
  food_chicken:{ id:'food_chicken',category:'food', name:'치킨 (야식)',         icon:'🍗', price:8,  desc:'HP +40 · 다음 전투 SP -10', effect:{ hp:40, battle_sp_penalty:10 } },
  food_cupramen:{ id:'food_cupramen',category:'food',name:'컵라면',             icon:'🥣', price:2,  desc:'HP +12 · SP +8',     effect:{ hp:12, sp:8 } },
  food_choco:  { id:'food_choco',  category:'food', name:'초코바',              icon:'🍫', price:3,  desc:'SP +15 · 집중력 +10% (1회)', effect:{ sp:15, focus_once:10 } },
  food_vita:   { id:'food_vita',   category:'food', name:'비타민 음료',         icon:'💊', price:10, desc:'최대 HP +5 (영구)',   effect:{ max_hp_perm:5 } },
  food_special:{ id:'food_special',category:'food', name:'학식 스페셜 정식',   icon:'🍽️', price:7,  desc:'HP +35 · SP +35',    effect:{ hp:35, sp:35 } },
  food_donut:  { id:'food_donut',  category:'food', name:'푸앙이 도넛',         icon:'🍩', price:8,  desc:'호감도 +8 · HP +10',  effect:{ favor:8, hp:10 } },
  food_makgeolli:{ id:'food_makgeolli',category:'food',name:'중앙대 막걸리',    icon:'🍶', price:5,  desc:'HP +30 · 명중률 -20% (1전투)', effect:{ hp:30, acc_penalty_once:20 } },
  food_icecream:{ id:'food_icecream',category:'food',name:'아이스크림',         icon:'🍦', price:2,  desc:'SP +12',             effect:{ sp:12 } },
  food_hotchoco:{ id:'food_hotchoco',category:'food',name:'핫초코',             icon:'🍵', price:3,  desc:'HP +18 · SP +8',     effect:{ hp:18, sp:8 } },
  food_salad:  { id:'food_salad',  category:'food', name:'과일 샐러드',         icon:'🥗', price:5,  desc:'HP +12 · 최대 HP +2 (영구)', effect:{ hp:12, max_hp_perm:2 } },
  food_protein:{ id:'food_protein',category:'food', name:'단백질 쉐이크',       icon:'🏋️', price:6,  desc:'체육관 효율 +30% (1회)', effect:{ gym_bonus_once:30 } },
  food_sandwich:{ id:'food_sandwich',category:'food',name:'편의점 샌드위치',    icon:'🥪', price:2,  desc:'HP +15 · SP +5',     effect:{ hp:15, sp:5 } },
  food_kimchi: { id:'food_kimchi', category:'food', name:'학식 김치찌개',       icon:'🫙', price:3,  desc:'HP +22',             effect:{ hp:22 } },
  food_takoyaki:{ id:'food_takoyaki',category:'food',name:'타코야끼',           icon:'🐙', price:4,  desc:'SP +18 · 호감도 +3',  effect:{ sp:18, favor:3 } },
  food_bungeoppang:{ id:'food_bungeoppang',category:'food',name:'붕어빵',       icon:'🐟', price:1,  desc:'HP +10 · 호감도 +2',  effect:{ hp:10, favor:2 } },
  food_tteok:  { id:'food_tteok',  category:'food', name:'떡볶이',              icon:'🌶️', price:4,  desc:'HP +20 · 전투 공격력 +3 (1회)', effect:{ hp:20, battle_dmg_once:3 } },
  food_maratang:{ id:'food_maratang',category:'food',name:'마라탕',             icon:'🫕', price:6,  desc:'HP +35 · SP -10',    effect:{ hp:35, sp:-10 } },
  food_sushi:  { id:'food_sushi',  category:'food', name:'초밥 세트',           icon:'🍣', price:10, desc:'HP +40 · SP +20',    effect:{ hp:40, sp:20 } },
  food_pizza:  { id:'food_pizza',  category:'food', name:'피자 한 조각',        icon:'🍕', price:5,  desc:'HP +25 · SP +10',    effect:{ hp:25, sp:10 } },
  food_burger: { id:'food_burger', category:'food', name:'햄버거 세트',         icon:'🍔', price:6,  desc:'HP +30 · SP +15',    effect:{ hp:30, sp:15 } },
  food_smoothie:{ id:'food_smoothie',category:'food',name:'스무디',             icon:'🍹', price:4,  desc:'SP +22 · 집중력 +5%', effect:{ sp:22, focus_once:5 } },
  food_honey:  { id:'food_honey',  category:'food', name:'꿀물',                icon:'🍯', price:2,  desc:'HP +8 · 상태이상 회복',effect:{ hp:8, cure:true } },
  food_hongsam:{ id:'food_hongsam',category:'food', name:'홍삼 음료',           icon:'🧃', price:12, desc:'최대 SP +5 (영구)',   effect:{ max_sp_perm:5 } },
  food_protinbar:{ id:'food_protinbar',category:'food',name:'프로틴 바',        icon:'🏃', price:7,  desc:'체육관 훈련 HP 보너스 +5', effect:{ gym_hp_bonus:5 } },
  food_donkatsu:{ id:'food_donkatsu',category:'food',name:'학식 돈까스',        icon:'🍖', price:5,  desc:'HP +28 · SP +12',    effect:{ hp:28, sp:12 } },
  food_cvs:    { id:'food_cvs',    category:'food', name:'편의점 도시락',       icon:'📦', price:3,  desc:'HP +20 · SP +8',     effect:{ hp:20, sp:8 } },
  food_blueberry:{ id:'food_blueberry',category:'food',name:'블루베리 스무디',  icon:'🫐', price:5,  desc:'도서관 집중력 +15% (1회)', effect:{ lib_focus_bonus_once:15 } },
  food_latte:  { id:'food_latte',  category:'food', name:'카페라떼',            icon:'🫗', price:3,  desc:'SP +18 · 호감도 +1',  effect:{ sp:18, favor:1 } },
  food_juice:  { id:'food_juice',  category:'food', name:'생과일주스',          icon:'🍊', price:4,  desc:'HP +15 · 독 디버프 제거', effect:{ hp:15, cure_poison:true } },
  food_macaron:{ id:'food_macaron',category:'food', name:'푸앙이 마카롱',       icon:'🫶', price:10, desc:'호감도 +12',          effect:{ favor:12 } },
  food_dragonball:{ id:'food_dragonball',category:'food',name:'청룡 에너지볼',  icon:'⚡', price:15, desc:'HP +20 · SP +20 · 전투 데미지 +3', effect:{ hp:20, sp:20, battle_dmg_once:3 } },
  food_naengmyeon:{ id:'food_naengmyeon',category:'food',name:'학식 냉면',      icon:'🍝', price:6,  desc:'SP +30 · HP +10',    effect:{ sp:30, hp:10 } },
  food_sotteok:{ id:'food_sotteok',category:'food', name:'소떡소떡',            icon:'🍡', price:3,  desc:'HP +18 · 호감도 +2',  effect:{ hp:18, favor:2 } },
  food_ssambap:{ id:'food_ssambap',category:'food', name:'중앙대 특제 쌈밥',   icon:'🥬', price:20, desc:'HP 완전 회복',         effect:{ hp_full:true } },
  food_potion_oth:{ id:'food_potion_oth',category:'food',name:'이면 세계 포션', icon:'🧪', price:25, desc:'HP +60 · SP +30',    effect:{ hp:60, sp:30 } },
  food_puang_special:{ id:'food_puang_special',category:'food',name:'푸앙이 특제 도시락',icon:'🐉',price:35,desc:'HP·SP 완전 회복 · 호감도 +5', effect:{ hp_full:true, sp_full:true, favor:5 } },
};
