// ================================================================
// items_equip.js — 착용 아이템 (50개)
// category: 'equip'
// 장착/해제 방식, 한 슬롯에 하나만
// ================================================================

window.ITEMS_EQUIP = {
  equip_001: {
    id: 'equip_001', category: 'equip',
    name: '중앙대 학생증', icon: '🪪', price: 8,
    desc: '최대 HP +10',
    effect: { max_hp: 10 },
  },
  equip_002: {
    id: 'equip_002', category: 'equip',
    name: '공대 점퍼', icon: '🧥', price: 10,
    desc: '전투 데미지 +5',
    effect: { battle_dmg: 5 },
  },
  equip_003: {
    id: 'equip_003', category: 'equip',
    name: '도서관 회원증', icon: '📗', price: 8,
    desc: '도서관 보상 +2',
    effect: { lib_reward: 2 },
  },
  equip_004: {
    id: 'equip_004', category: 'equip',
    name: '청룡 배지', icon: '🏅', price: 20,
    desc: '모든 스탯 +5%',
    effect: { all_stat_pct: 5 },
  },
  equip_005: {
    id: 'equip_005', category: 'equip',
    name: '푸앙이 머플러', icon: '🧣', price: 15,
    desc: '피해 감소 10%',
    effect: { dmg_reduce_pct: 10 },
  },
  equip_006: {
    id: 'equip_006', category: 'equip',
    name: '이면 세계 코트', icon: '🥼', price: 18,
    desc: '전투 시작 HP +20',
    effect: { battle_start_hp: 20 },
  },
  equip_007: {
    id: 'equip_007', category: 'equip',
    name: '이어폰', icon: '🎧', price: 8,
    desc: '도서관 보상 +2',
    effect: { lib_reward: 2 },
  },
  equip_008: {
    id: 'equip_008', category: 'equip',
    name: '노트북 가방', icon: '🎒', price: 10,
    desc: '데이터 조각 보관량 +20',
    effect: { data_capacity: 20 },
  },
  equip_009: {
    id: 'equip_009', category: 'equip',
    name: '중앙대 후드티', icon: '👕', price: 12,
    desc: '방어력 + 호감도 +3',
    effect: { defense: 3, favor: 3 },
  },
  equip_010: {
    id: 'equip_010', category: 'equip',
    name: '스터디 플래너', icon: '📒', price: 10,
    desc: '공부 횟수 +2',
    effect: { study_count: 2 },
  },
  equip_011: {
    id: 'equip_011', category: 'equip',
    name: '보조배터리', icon: '🔋', price: 14,
    desc: 'SP 매 턴 +3 자동회복',
    effect: { sp_regen_per_turn: 3 },
  },
  equip_012: {
    id: 'equip_012', category: 'equip',
    name: '청룡 안경', icon: '👓', price: 15,
    desc: '적 약점 노출 +20%',
    effect: { weakness_reveal_pct: 20 },
  },
  equip_013: {
    id: 'equip_013', category: 'equip',
    name: '공학 계산기', icon: '🔢', price: 12,
    desc: '데미지 +3',
    effect: { battle_dmg: 3 },
  },
  equip_014: {
    id: 'equip_014', category: 'equip',
    name: '중앙대 체육복', icon: '🩱', price: 10,
    desc: '체육관 훈련 효율 +50%',
    effect: { gym_efficiency_pct: 50 },
  },
  equip_015: {
    id: 'equip_015', category: 'equip',
    name: '두꺼운 전공책', icon: '📚', price: 14,
    desc: '피해 -8',
    effect: { dmg_reduce: 8 },
  },
  equip_016: {
    id: 'equip_016', category: 'equip',
    name: '행운의 동전', icon: '🪙', price: 18,
    desc: '주사위 최솟값 +2',
    effect: { dice_min: 2 },
  },
  equip_017: {
    id: 'equip_017', category: 'equip',
    name: '블루미르 목걸이', icon: '📿', price: 16,
    desc: '호감도 +5 · 최대 SP +5',
    effect: { favor: 5, max_sp: 5 },
  },
  equip_018: {
    id: 'equip_018', category: 'equip',
    name: '무선 이어버드', icon: '🎵', price: 12,
    desc: '도서관 집중력 감소 -10%',
    effect: { lib_focus_decay_pct: -10 },
  },
  equip_019: {
    id: 'equip_019', category: 'equip',
    name: '캠퍼스 자전거', icon: '🚲', price: 8,
    desc: '이동 SP 소모 없음',
    effect: { move_sp_cost: 0 },
  },
  equip_020: {
    id: 'equip_020', category: 'equip',
    name: '학생회 완장', icon: '🎖️', price: 14,
    desc: '축제 보상 +50%',
    effect: { festival_reward_pct: 50 },
  },
  equip_021: {
    id: 'equip_021', category: 'equip',
    name: '연구실 열쇠', icon: '🔑', price: 16,
    desc: '310관 강화 비용 -20%',
    effect: { lab_cost_pct: -20 },
  },
  equip_022: {
    id: 'equip_022', category: 'equip',
    name: '이면 세계 망토', icon: '🦸', price: 20,
    desc: '진입 시 HP +10%',
    effect: { enter_hp_pct: 10 },
  },
  equip_023: {
    id: 'equip_023', category: 'equip',
    name: '청룡산 등산화', icon: '👟', price: 22,
    desc: '보스 HP -10%',
    effect: { boss_hp_pct: -10 },
  },
  equip_024: {
    id: 'equip_024', category: 'equip',
    name: '중앙대 졸업반지', icon: '💍', price: 50,
    desc: '모든 효과 +10%',
    effect: { all_effect_pct: 10 },
  },
  equip_025: {
    id: 'equip_025', category: 'equip',
    name: '청룡 방패', icon: '🛡️', price: 25,
    desc: '피해 -15 · 최대 HP +10',
    effect: { dmg_reduce: 15, max_hp: 10 },
  },
  equip_026: {
    id: 'equip_026', category: 'equip',
    name: '연구원 가운', icon: '🥽', price: 12,
    desc: '실험실 제조 비용 -2',
    effect: { lab2_cost: -2 },
  },
  equip_027: {
    id: 'equip_027', category: 'equip',
    name: '스포츠 밴드', icon: '⌚', price: 10,
    desc: '체육관 체력 소모 -10%',
    effect: { gym_hp_cost_pct: -10 },
  },
  equip_028: {
    id: 'equip_028', category: 'equip',
    name: '캠퍼스 지도', icon: '🗺️', price: 5,
    desc: '장소 툴팁 상세 표시',
    effect: { map_tooltip_detail: true },
  },
  equip_029: {
    id: 'equip_029', category: 'equip',
    name: '학식 쿠폰북', icon: '🎟️', price: 15,
    desc: '학생식당 가격 -1 (영구)',
    effect: { cafeteria_cost: -1 },
  },
  equip_030: {
    id: 'equip_030', category: 'equip',
    name: '청룡 깃털 펜', icon: '🪶', price: 10,
    desc: '퀴즈 정답 보상 +3',
    effect: { quiz_reward: 3 },
  },
  equip_031: {
    id: 'equip_031', category: 'equip',
    name: '마법 노트', icon: '📓', price: 14,
    desc: '도서관 보상 최솟값 +1',
    effect: { lib_reward_min: 1 },
  },
  equip_032: {
    id: 'equip_032', category: 'equip',
    name: '중앙대 야구 모자', icon: '🧢', price: 8,
    desc: '햇빛 디버프 면역',
    effect: { sunlight_immune: true },
  },
  equip_033: {
    id: 'equip_033', category: 'equip',
    name: '공대 로봇 부품', icon: '🤖', price: 20,
    desc: '전투 자동 방어 1회',
    effect: { auto_shield: 1 },
  },
  equip_034: {
    id: 'equip_034', category: 'equip',
    name: '이면 세계 장갑', icon: '🖐️', price: 22,
    desc: '크리티컬 확률 +15%',
    effect: { crit_pct: 15 },
  },
  equip_035: {
    id: 'equip_035', category: 'equip',
    name: '블루미르 부적', icon: '🧿', price: 30,
    desc: '전투 패배 시 HP 1 유지 (1회)',
    effect: { last_stand: 1 },
  },
  equip_036: {
    id: 'equip_036', category: 'equip',
    name: '청룡 문신 스티커', icon: '🔱', price: 18,
    desc: '전투 데미지 +8',
    effect: { battle_dmg: 8 },
  },
  equip_037: {
    id: 'equip_037', category: 'equip',
    name: '중앙대 스카프', icon: '🎀', price: 20,
    desc: '최대 HP +15 · 최대 SP +5',
    effect: { max_hp: 15, max_sp: 5 },
  },
  equip_038: {
    id: 'equip_038', category: 'equip',
    name: '연구실 고글', icon: '🔭', price: 12,
    desc: '실험실 성공률 +20%',
    effect: { lab2_success_pct: 20 },
  },
  equip_039: {
    id: 'equip_039', category: 'equip',
    name: '푸앙이 배낭', icon: '🪅', price: 15,
    desc: '인벤토리 슬롯 +3',
    effect: { inv_slots: 3 },
  },
  equip_040: {
    id: 'equip_040', category: 'equip',
    name: '청룡 시계', icon: '⏱️', price: 16,
    desc: '도서관 공부 시간 -1초',
    effect: { lib_time: -1 },
  },
  equip_041: {
    id: 'equip_041', category: 'equip',
    name: '중앙대 체인', icon: '⛓️', price: 24,
    desc: '보스 등장 시 데미지 +10',
    effect: { boss_dmg: 10 },
  },
  equip_042: {
    id: 'equip_042', category: 'equip',
    name: '이면 세계 부츠', icon: '👢', price: 20,
    desc: '전투 회피율 +10%',
    effect: { dodge_pct: 10 },
  },
  equip_043: {
    id: 'equip_043', category: 'equip',
    name: '학생처 도장', icon: '🔏', price: 18,
    desc: '의무실 무료 횟수 +1',
    effect: { clinic_free: 1 },
  },
  equip_044: {
    id: 'equip_044', category: 'equip',
    name: '청룡 왕관', icon: '👑', price: 40,
    desc: '호감도 +10 · 모든 스탯 +3%',
    effect: { favor: 10, all_stat_pct: 3 },
  },
  equip_045: {
    id: 'equip_045', category: 'equip',
    name: '마법 계산기', icon: '🎰', price: 15,
    desc: '슬롯머신 당첨 확률 +5%',
    effect: { slot_luck_pct: 5 },
  },
  equip_046: {
    id: 'equip_046', category: 'equip',
    name: '이면 세계 검', icon: '⚔️', price: 28,
    desc: '전투 데미지 +12 · 방어 -5',
    effect: { battle_dmg: 12, dmg_reduce: -5 },
  },
  equip_047: {
    id: 'equip_047', category: 'equip',
    name: '블루미르 방패', icon: '🔰', price: 28,
    desc: '피해 -20 · 데미지 -5',
    effect: { dmg_reduce: 20, battle_dmg: -5 },
  },
  equip_048: {
    id: 'equip_048', category: 'equip',
    name: '청룡 갑옷', icon: '🪬', price: 45,
    desc: '최대 HP +30 · 피해 -10',
    effect: { max_hp: 30, dmg_reduce: 10 },
  },
  equip_049: {
    id: 'equip_049', category: 'equip',
    name: '이면 세계 마법서', icon: '📖', price: 48,
    desc: '모든 스킬 데미지 +20%',
    effect: { skill_dmg_pct: 20 },
  },
  equip_050: {
    id: 'equip_050', category: 'equip',
    name: '푸앙이 성물', icon: '✨', price: 99,
    desc: '모든 스탯 최대 · 호감도 +20',
    effect: { all_stat_max: true, favor: 20 },
  },
};
