// ================================================================
// items_deco.js — 꾸미기 아이템 (50개)
// category: 'deco'
// slot: 배치될 방 슬롯 (puang_room.js의 roomDecorations 키와 일치)
// ================================================================
window.ITEMS_DECO = {
  // ── 기존 ROOM_ITEMS와 id 호환 유지 ──
  item_bed:             { id:'item_bed',             category:'deco', slot:'bed',             name:'블루 체크 침대',         icon:'🛏️', price:20, desc:'포근한 블루 체크 침대' },
  item_desk:            { id:'item_desk',             category:'deco', slot:'desk',            name:'달빛 컴퓨터 책상',       icon:'💻', price:18, desc:'밤하늘 모니터가 있는 책상' },
  item_carpet:          { id:'item_carpet',           category:'deco', slot:'carpet',          name:'블루 플로럴 카펫',       icon:'🟦', price:12, desc:'꽃무늬 블루 카펫' },
  item_bookshelf_small: { id:'item_bookshelf_small',  category:'deco', slot:'bookshelf_small', name:'작은 책장',             icon:'📚', price:14, desc:'푸앙이 인형이 앉아있는 작은 책장' },
  item_bookshelf_big:   { id:'item_bookshelf_big',    category:'deco', slot:'bookshelf_big',   name:'큰 책장',               icon:'📖', price:22, desc:'책과 소품이 가득한 큰 책장' },
  item_lamp:            { id:'item_lamp',             category:'deco', slot:'lamp',            name:'플로럴 스탠드 조명',     icon:'🌟', price:10, desc:'꽃무늬 스탠드 조명' },
  item_hanging_plant:   { id:'item_hanging_plant',    category:'deco', slot:'hanging_plant',   name:'행잉 화분',             icon:'🪴', price:8,  desc:'천장에 매달린 행잉 화분' },
  item_shelf_left:      { id:'item_shelf_left',       category:'deco', slot:'shelf_left',      name:'벽 선반 (왼쪽)',        icon:'🔖', price:15, desc:'왼쪽 벽에 달린 책·화분 선반' },
  item_shelf_right:     { id:'item_shelf_right',      category:'deco', slot:'shelf_right',     name:'벽 선반 (오른쪽)',      icon:'🔖', price:15, desc:'오른쪽 벽에 달린 선반' },
  item_painting_left:   { id:'item_painting_left',    category:'deco', slot:'painting_left',   name:'달밤 액자 (왼쪽)',      icon:'🖼️', price:10, desc:'왼쪽 벽의 달밤 그림 액자' },
  item_painting_right:  { id:'item_painting_right',   category:'deco', slot:'painting_right',  name:'꽃 액자 (오른쪽)',      icon:'🖼️', price:10, desc:'오른쪽 벽의 꽃 그림 액자' },
  item_wall_plant:      { id:'item_wall_plant',       category:'deco', slot:'wall_plant',      name:'벽 화분 장식',          icon:'🌿', price:9,  desc:'벽에 달린 식물 화분' },
  item_hanging_deco:    { id:'item_hanging_deco',     category:'deco', slot:'hanging_deco',    name:'행잉 장식',             icon:'✨', price:11, desc:'달과 별 모양 행잉 장식' },
  item_memo_poster:     { id:'item_memo_poster',      category:'deco', slot:'memo_poster',     name:'메모 포스터',           icon:'📌', price:8,  desc:'달밤 사진 & 메모 포스터' },
  item_dreamcatcher:    { id:'item_dreamcatcher',     category:'deco', slot:'dreamcatcher',    name:'드림캐처',              icon:'🌙', price:13, desc:'블루 드림캐처 장식' },
  item_night:           { id:'item_night',            category:'deco', slot:'background',      theme:'night',  name:'블루미르홀 야경 사진',   icon:'🌃', price:13, desc:'방 야경 테마로 변경' },
  item_sakura:          { id:'item_sakura',           category:'deco', slot:'background',      theme:'sakura', name:'캠퍼스 벚꽃 화분',      icon:'🌸', price:8,  desc:'방 봄 테마로 변경' },
  item_dark:            { id:'item_dark',             category:'deco', slot:'background',      theme:'dark',   name:'이면 세계 암흑 결정',   icon:'🖤', price:32, desc:'방 다크 테마로 변경' },
  item_tank:            { id:'item_tank',             category:'deco', slot:'wall2',           name:'청룡 어항',             icon:'🐠', price:14, desc:'벽 오른쪽 어항 장식' },
  item_doll:            { id:'item_doll',             category:'deco', slot:'wall2',           name:'푸앙이 인형',           icon:'🧸', price:11, desc:'벽 오른쪽 인형 장식' },
  item_trophy:          { id:'item_trophy',           category:'deco', slot:'wall2',           name:'이면세계 트로피',       icon:'🏆', price:18, desc:'전투 승리 기념 트로피' },

  // ── 신규 꾸미기 아이템 ──
  deco_flag:     { id:'deco_flag',     category:'deco', slot:'wall',          name:'블루미르 깃발',         icon:'🚩', price:5,  desc:'방 배경 변경' },
  deco_banner:   { id:'deco_banner',   category:'deco', slot:'wall',          name:'중앙대 현수막',         icon:'🎌', price:6,  desc:'방 분위기 변경' },
  deco_poster:   { id:'deco_poster',   category:'deco', slot:'memo_poster',   name:'이면 세계 포스터',      icon:'📜', price:9,  desc:'방 포스터 추가' },
  deco_school_flag:{ id:'deco_school_flag',category:'deco',slot:'wall',       name:'중앙대 교기',           icon:'🏴', price:12, desc:'방 특별 배경' },
  deco_calendar: { id:'deco_calendar', category:'deco', slot:'wall2',         name:'푸앙이 달력',           icon:'📅', price:15, desc:'일일 보너스 활성화', effect:{ daily_bonus:true } },
  deco_aquarium: { id:'deco_aquarium', category:'deco', slot:'wall2',         name:'블루미르 수족관',       icon:'🐠', price:20, desc:'방에 물고기 장식' },
  deco_cheer:    { id:'deco_cheer',    category:'deco', slot:'wall',          name:'응원 현수막',           icon:'🎊', price:10, desc:'전투 사기 +5%', effect:{ battle_morale_pct:5 } },
  deco_statue:   { id:'deco_statue',   category:'deco', slot:'floor',         name:'청룡 조각상',           icon:'🗿', price:18, desc:'방 위엄 UP' },
  deco_clock:    { id:'deco_clock',    category:'deco', slot:'shelf_left',    name:'중앙대 시계탑 미니어처', icon:'🕰️', price:14, desc:'방 클래식 테마' },
  deco_crystal:  { id:'deco_crystal',  category:'deco', slot:'shelf_right',   name:'이면 세계 수정구',      icon:'🔮', price:16, desc:'방 신비 테마' },
  deco_photoframe:{ id:'deco_photoframe',category:'deco',slot:'painting_right',name:'푸앙이 사진액자',      icon:'🪞', price:10, desc:'호감도 +3', effect:{ favor:3 } },
  deco_campusmap:{ id:'deco_campusmap',category:'deco', slot:'painting_left', name:'캠퍼스 지도 액자',      icon:'🗾', price:12, desc:'방 탐험가 테마' },
  deco_mountain: { id:'deco_mountain', category:'deco', slot:'painting_left', name:'청룡산 풍경화',         icon:'🏔️', price:11, desc:'방 자연 테마' },
  deco_album:    { id:'deco_album',    category:'deco', slot:'shelf_left',    name:'중앙대 졸업 앨범',      icon:'📸', price:15, desc:'방 추억 테마' },
  deco_otherworld_map:{ id:'deco_otherworld_map',category:'deco',slot:'wall', name:'이면 세계 지도',        icon:'🧭', price:20, desc:'새 던전 힌트 제공', effect:{ dungeon_hint:true } },
  deco_curtain:  { id:'deco_curtain',  category:'deco', slot:'hanging_deco',  name:'반짝이 커튼',           icon:'🌠', price:9,  desc:'방 화려 테마' },
  deco_plushset: { id:'deco_plushset', category:'deco', slot:'shelf_right',   name:'푸앙이 봉제인형 세트',  icon:'🐲', price:22, desc:'방 귀여운 테마' },
  deco_lantern:  { id:'deco_lantern',  category:'deco', slot:'lamp',          name:'캠퍼스 가로등 미니어처', icon:'🪔', price:14, desc:'방 빈티지 조명' },
  deco_dragonflag:{ id:'deco_dragonflag',category:'deco',slot:'wall',         name:'청룡 깃발 세트',        icon:'🎏', price:16, desc:'방 전통 테마' },
  deco_crack:    { id:'deco_crack',    category:'deco', slot:'wall',          theme:'dark', name:'이면 세계 균열 장식', icon:'💠', price:18, desc:'방 이면 테마' },
  deco_trophy2:  { id:'deco_trophy2',  category:'deco', slot:'wall2',         name:'중앙대 트로피',         icon:'🏆', price:20, desc:'방 명예 테마' },
  deco_stars:    { id:'deco_stars',    category:'deco', slot:'hanging_deco',  name:'별자리 천장 장식',      icon:'🌌', price:17, desc:'방 우주 테마' },
  deco_carpet2:  { id:'deco_carpet2',  category:'deco', slot:'carpet',        name:'푸앙이 발자국 카펫',    icon:'👣', price:12, desc:'방 바닥 꾸미기' },
  deco_pool:     { id:'deco_pool',     category:'deco', slot:'shelf_left',    name:'청룡탕 미니어처',       icon:'🏊', price:13, desc:'방 여름 테마' },
  deco_bug:      { id:'deco_bug',      category:'deco', slot:'shelf_right',   name:'이면 세계 버그 표본',   icon:'🔬', price:11, desc:'방 연구자 테마' },
  deco_robot:    { id:'deco_robot',    category:'deco', slot:'shelf_left',    name:'공대 로봇 피규어',      icon:'🦾', price:16, desc:'방 공학 테마' },
  deco_libshelf: { id:'deco_libshelf', category:'deco', slot:'bookshelf_small',name:'도서관 미니어처 책장',  icon:'🗂️', price:14, desc:'방 학구 테마' },
  deco_fountain: { id:'deco_fountain', category:'deco', slot:'floor',         name:'캠퍼스 분수대 피규어',  icon:'⛲', price:18, desc:'방 중앙 광장 테마' },
  deco_dragon:   { id:'deco_dragon',   category:'deco', slot:'floor',         name:'청룡 이무기 피규어',    icon:'🐍', price:22, desc:'방 전설 테마' },
  deco_moon:     { id:'deco_moon',     category:'deco', slot:'hanging_deco',  name:'이면 세계 달 장식',     icon:'🌕', price:15, desc:'방 밤 테마' },
  deco_party:    { id:'deco_party',    category:'deco', slot:'wall',          name:'푸앙이 생일 파티 세트', icon:'🎉', price:20, desc:'방 파티 테마' },
  deco_brick:    { id:'deco_brick',    category:'deco', slot:'wall',          name:'중앙대 벽돌 장식',      icon:'🧱', price:10, desc:'방 고딕 테마' },
  deco_flame:    { id:'deco_flame',    category:'deco', slot:'wall',          name:'청룡 불꽃 장식',        icon:'🔥', price:17, desc:'방 열정 테마' },
  deco_portal:   { id:'deco_portal',   category:'deco', slot:'floor',         name:'이면 세계 포탈 미니어처',icon:'🌀', price:25, desc:'방 포탈 테마' },
  deco_menu:     { id:'deco_menu',     category:'deco', slot:'wall',          name:'학식 메뉴판 액자',      icon:'🪧', price:8,  desc:'방 맛집 테마' },
  deco_autumn:   { id:'deco_autumn',   category:'deco', slot:'hanging_plant', name:'캠퍼스 단풍 화분',      icon:'🍂', price:9,  desc:'방 가을 테마' },
  deco_snow:     { id:'deco_snow',     category:'deco', slot:'hanging_deco',  name:'청룡 눈꽃 장식',        icon:'❄️', price:9,  desc:'방 겨울 테마' },
  deco_lightning:{ id:'deco_lightning',category:'deco', slot:'wall',          name:'이면 세계 번개 장식',   icon:'🌩️', price:12, desc:'방 전기 테마' },
  deco_throne:   { id:'deco_throne',   category:'deco', slot:'floor',         name:'푸앙이 왕좌 미니어처',  icon:'🪑', price:30, desc:'방 왕실 테마' },
  deco_campus:   { id:'deco_campus',   category:'deco', slot:'floor',         name:'중앙대 캠퍼스 모형',    icon:'🏛️', price:35, desc:'방 캠퍼스 테마' },
  deco_aura:     { id:'deco_aura',     category:'deco', slot:'hanging_deco',  name:'청룡 오라 장식',        icon:'💫', price:28, desc:'방 신성 테마' },
  deco_golden:   { id:'deco_golden',   category:'deco', slot:'floor',         name:'푸앙이 황금 조각상',    icon:'🥇', price:45, desc:'방 황금 테마 · 호감도 +5', effect:{ favor:5 } },
  deco_signboard:{ id:'deco_signboard',category:'deco', slot:'wall',          name:'중앙대 푸앙월드 간판',  icon:'🎆', price:80, desc:'방 최고급 테마 · 모든 장식 효과 2배', effect:{ deco_effect_multiplier:2 } },
};
